name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build (CGO)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '>= 1.20'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools (Unix)
      if: runner.os != 'Windows'
      run: |
        go install golang.org/x/lint/golint@latest

    - uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'

    - name: Install Tools (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |+
        pacman.exe -Sy --noconfirm libxml2-devel mingw-w64-x86_64-go pkg-config
        pkg-config.exe --libs libxml2-devel
      env:
        PKG_CONFIG_PATH: "C:\\msys64\\usr\\lib\\pkgconfig:C:\\msys64\\usr\\include\\libxml2\\"

    - name: Test (Unix)
      if: runner.os != 'Windows'
      run: |
        go vet ./...
        golint ./...
        go test -cover -v ./...

    - name: Test (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |+
        go.exe test -v ./...
      env:
        CGO_CFLAGS: "-O2 -g -IC:\\msys64\\usr\\include\\libxml2\\"
        CGO_LDFLAGS: "-O2 -g -LC:\\msys64\\usr\\include\\libxml2\\ -Wl,-rpath,C:\\msys64\\usr\\include\\libxml2\\"
        PKG_CONFIG_PATH: "C:\\msys64\\usr\\lib\\pkgconfig"
